# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl: ""
url: ""
date_format: "ordinal"
title: 赵延生的个人博客
subtitle: "不知道说些什么，先空着吧!"
description: "赵延生的个人博客"
keywords: 赵延生, 软件开发工程师, 软件架构工程师
# 网站网址栏展示的图标
favicon: /favicon.ico
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#     作者信息      #
# ---------------- #
author: 赵延生
# 公司名称 网站
organization: hao99
organization_url: https://blog.hao99.cn/
github_username: zhaoyansheng163
location: 深圳, 中国
email: 35933019@qq.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: zhaoyansheng163/zhaoyansheng163.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
#gitment:
#    owner: zhaoyansheng163
#    repo: blog-comments
#    oauth:
#        client_id: 1d77e991408012a46cc3
#        client_secret: 36c68a7e2399cc16516a91766597e54a3d046859
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: zhaoyansheng163
    repo: blog-comments
    clientID: 1d77e991408012a46cc3
    clientSecret: 36c68a7e2399cc16516a91766597e54a3d046859
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
#google:
#    analytics_id: UA-80669434-1

theme: jekyll-theme-cayman